# Generated by Django 3.1.2 on 2020-10-24 05:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_pk', models.IntegerField(blank=True)),
                ('nickname', models.CharField(blank=True, max_length=200)),
                ('profile_image', models.ImageField(blank=True, default='images/default.png', null=True, upload_to='images/')),
                ('service_place', models.CharField(blank=True, max_length=200)),
                ('birth', models.CharField(blank=True, max_length=8)),
                ('age', models.IntegerField(default=70)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Box',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qr_img', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('box_number', models.CharField(blank=True, max_length=20, unique=True)),
                ('customer_location', models.CharField(blank=True, max_length=200)),
                ('customer_phonenum', models.CharField(blank=True, max_length=200)),
                ('customer_name', models.CharField(blank=True, max_length=200)),
                ('started_at', models.CharField(blank=True, max_length=20, null=True)),
                ('completed_at', models.CharField(blank=True, max_length=20, null=True)),
                ('status', models.CharField(blank=True, choices=[('W', '배송 대기'), ('D', '배송 중'), ('C', '배송 완료')], default='W', max_length=100)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
