# Generated by Django 3.1.2 on 2020-10-17 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='box',
            name='completed_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='box',
            name='started_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
