# Generated by Django 3.1.2 on 2020-10-17 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20201017_2213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='box',
            name='completed_at',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='box',
            name='started_at',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
