# Generated by Django 3.1.2 on 2020-10-21 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20201021_1840'),
    ]

    operations = [
        migrations.AddField(
            model_name='box',
            name='qr_img',
            field=models.ImageField(blank=True, default='images/qr4685958419.png', null=True, upload_to='images/'),
        ),
    ]
