# Generated by Django 3.1.2 on 2020-10-11 09:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0003_profile_profile_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service_Place',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valid_place', models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Box',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('box_number', models.CharField(blank=True, max_length=20, unique=True)),
                ('customer_location', models.CharField(blank=True, max_length=200)),
                ('customer_phonenum', models.CharField(blank=True, max_length=200)),
                ('customer_name', models.CharField(blank=True, max_length=200)),
                ('status', models.CharField(blank=True, choices=[('W', '배송 대기'), ('D', '배송 중'), ('C', '배송 완료')], max_length=100)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='profile',
            name='service_place',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.service_place'),
        ),
    ]
