# Generated by Django 3.1.2 on 2020-10-11 09:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20201011_1807'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='service_place',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.service_place'),
        ),
    ]
