# Generated by Django 3.1.2 on 2020-10-10 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_box'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service_Place',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valid_place', models.CharField(blank=True, max_length=200)),
            ],
        ),
    ]
