# Generated by Django 3.1.2 on 2020-10-10 15:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_service_place'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='service_place',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.service_place'),
        ),
    ]
