# Generated by Django 3.1.2 on 2020-10-11 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_profile_service_place'),
    ]

    operations = [
        migrations.AlterField(
            model_name='box',
            name='box_number',
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='box',
            name='status',
            field=models.CharField(blank=True, choices=[('W', '배송 대기'), ('D', '배송 중'), ('C', '배송 완료')], max_length=100),
        ),
    ]
