# Generated by Django 3.1.2 on 2020-10-11 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20201011_1230'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service_place',
            name='id',
        ),
        migrations.AlterField(
            model_name='service_place',
            name='valid_place',
            field=models.CharField(max_length=200, primary_key=True, serialize=False),
        ),
    ]
