# Generated by Django 3.1.2 on 2020-10-15 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20201015_2343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='service_place',
            field=models.CharField(blank=True, default=12, max_length=200),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Service_Place',
        ),
    ]
