# Generated by Django 3.1.2 on 2020-10-21 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20201021_1858'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='box',
            name='qr_img',
        ),
    ]
