# Generated by Django 3.1.2 on 2020-10-21 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_remove_box_qr_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='box',
            name='qr_img',
            field=models.ImageField(blank=True, default='images/qr2674361914.png', null=True, upload_to='images/'),
        ),
    ]
