# Generated by Django 3.1.2 on 2020-10-21 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_box_qr_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='box',
            name='qr_img',
            field=models.ImageField(blank=True, default='images/qr7206898868.png', null=True, upload_to='images/'),
        ),
    ]
