# Generated by Django 3.1.2 on 2020-10-21 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_auto_20201021_1905'),
    ]

    operations = [
        migrations.AlterField(
            model_name='box',
            name='qr_img',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='box',
            name='status',
            field=models.CharField(blank=True, choices=[('W', '배송 대기'), ('D', '배송 중'), ('C', '배송 완료')], default='W', max_length=100),
        ),
    ]
